[package]
name = "rust_compiler_construction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
thiserror = "1.0.46"
once_cell = "1.18.0"
regex = "1.9.3"
