[package]
name = "rust_compiler_construction"
version = "0.1.0"
edition = "2021"
authors = ["joooooooonaaaaa", "juuuuuuuuuuuuuuuuuuliaaaaaaaaaa"]

[dependencies]
nom = "7.1.3"
thiserror = "1.0.46"
once_cell = "1.18.0"
regex = "1.9.3"
tempdir = "0.3.7"

[dev-dependencies]
test_each_file = "0.1.0"
