[package]
name = "bencher"
version = "0.1.0"
edition = "2021"
authors = ["joooooooonaaaaa", "juuuuuuuuuuuuuuuuuuliaaaaaaaaaa"]

[dependencies]
itertools = "0.11.0"
mongodb = "2.7.0"
pathdiff = "0.2.1"
serde = "1.0.189"
tempdir = "0.3.7"
walkdir = "2.4.0"
