name: Rust

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CC

    steps:
      - uses: actions/checkout@v3
      - name: Build main
        run: cargo build --verbose
      - name: Cargo fmt
        run: cargo fmt --check
      - name: Cargo clippy
        run: cargo clippy -- -D warnings
      - name: Run tests
        run: cargo test --verbose
      - name: Run regression tests
        env:
          MONGO_PW: ${{ secrets.MONGO_PW }}
        run: cargo run --bin bencher --features bench

